entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: "dmitrii.timoshenko16@gmail.com"
      storage: "/etc/traefik/acme/acme.json"
      httpChallenge:
        entryPoint: "web"

log:
  level: DEBUG
  filePath: "/var/log/traefik/traefik.log"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
