entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: "${TRAEFIK_ACME_EMAIL}"
      storage: "${TRAEFIK_ACME_STORAGE}"
      httpChallenge:
        entryPoint: "web"

log:
  level: WARN
  filePath: "/var/log/traefik/traefik.log"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
