profile: cover.out

threshold:
  # Minimum coverage percentage required for individual files.
  file: 0

  # Minimum coverage percentage required for each package.
  package: 0

  # Minimum overall project coverage percentage required.
  total: 0

exclude:
  paths:
    - ^/vendor

breakdown-file-name: ''

diff:
  base-breakdown-file-name: ''
